export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_POST_BY_ID_FAIL = 'FETCH_POST_BY_ID_FAIL';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
